### PR TITLE
Setup test kitchen

### PR DESCRIPTION
**Pull request by afred**
This satisfies the **done when** for issue #1, however, the tests aren't passing. Since our cookbooks are small customizations to be run in conjunction with several recipes provided by AWS Opsworks, we need to bring those in as dependencies.

I'm still new to the platform, but I think the best tool for doing this is Berkshelf. Creating an new issue for that.

### CODE REVIEW

**Comment by afred** [comment]
@mccalluc please review

**Comment by mccalluc** [comment]
@afred: should I be able to run something here to make me more confident that it's doing the right thing?

**Comment by afred** [comment]
@mccalluc ideally yes, but it takes a little setup.

The `test-kitchen` gem is a way to run chef recipes on local vm's for testing infrastructure code. By default it uses vagrant and virtualbox, so you'd need those installed. After that, you should be able to run...
```
gem install test-kitchen
git clone git@github.com:WGBH/aapb-cookbooks.git
cd aapb-cookbooks/aapb_setup
kitchen converge
```
as mentioned above, the goal of this is to just get `test-kitchen` to run, even with failing tests. Fixes coming in future PRs.

**Comment by mccalluc** [comment]
@afred: Sorry to be obstinate on this:
```
[aapb_setup]$ git checkout setup-test-kitchen
Branch setup-test-kitchen set up to track remote branch setup-test-kitchen from origin.
Switched to a new branch 'setup-test-kitchen'
[aapb_setup]$ kitchen converge
-----> Starting Kitchen (v1.4.2)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'vagrant' driver from the load path. Please ensure that your driver is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
[aapb_setup]$ which vagrant
/usr/local/bin/vagrant
[aapb_setup]$ ls -d /Applications/VirtualBox.app
/Applications/VirtualBox.app
```

I think I'm still missing something?

**Pull request merged**
